version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db          # ✅ just the hostname of the MySQL container
      - MYSQL_PORT=3306        # ✅ specify port separately
      - MYSQL_USER=pymsql
      - MYSQL_PASSWORD=pymsql123
      - MYSQL_DB=employees
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pymsql123
      - MYSQL_DATABASE=employees
      - MYSQL_USER=pymsql
      - MYSQL_PASSWORD=pymsql123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    

volumes:
  mysql-data:
